name: Build Tweak

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: brew install dpkg

      - name: Clone Theos
        run: git clone --recursive https://github.com/theos/theos.git $HOME/theos

      - name: Set THEOS
        run: echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Build
        run: make package FINALPACKAGE=1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tweak
          path: packages/*.deb
